FROM almalinux:9

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN set -eux; \
    dnf check-update && dnf update -y ; \
    dnf install -y \
    pkgconf \
    clang \
    make \
    openssl-devel \
    krb5-devel ; \
    dnf clean all ; \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path ; \
    cargo install cargo-generate-rpm ;

WORKDIR /SRC