FROM rust:slim-bullseye

RUN set -eux; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    pkgconf \
    clang \
    make \
    libssl-dev \
    libkrb5-dev && \
    cargo install cargo-deb

WORKDIR /SRC
